name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build and check with Gradle
        run: ./gradlew check

      # Optional: Remove the following sections if you no longer use text-ui-test
      - name: Install dos2unix on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Perform IO redirection test (*NIX or macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        working-directory: ${{ github.workspace }}/text-ui-test
        run: |
          dos2unix runtest.sh
          ./runtest.sh

      - name: Perform IO redirection test (Windows)
        if: always() && runner.os == 'Windows'
        working-directory: ${{ github.workspace }}/text-ui-test
        shell: cmd
        run: runtest.bat